// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABzTI8kVwtAC1rbv39JD_THbLWmQAIQMY',
    appId: '1:553578579474:web:f13313d03d3cb328e3facb',
    messagingSenderId: '553578579474',
    projectId: 'my-new-gorlf',
    authDomain: 'my-new-gorlf.firebaseapp.com',
    storageBucket: 'my-new-gorlf.firebasestorage.app',
    measurementId: 'G-NVK5ZWZP3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ90H7S3JT1r-aGxCu4KxzXyjmzcEc1SE',
    appId: '1:553578579474:android:3118058690ebb1b6e3facb',
    messagingSenderId: '553578579474',
    projectId: 'my-new-gorlf',
    storageBucket: 'my-new-gorlf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyhSENo8-_Z1-A9u7QsrGdRW3AliSKxk',
    appId: '1:553578579474:ios:9a3754ba4a34b31ae3facb',
    messagingSenderId: '553578579474',
    projectId: 'my-new-gorlf',
    storageBucket: 'my-new-gorlf.firebasestorage.app',
    iosBundleId: 'com.orly.ramirez.myNewGorlf',
  );
}
